[package]
name = "easyssh"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8.*"
shell-escape = "0.1.*"